Added --enable-pab-wilson-dslash

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_STRING='chroma 1.5'
 PACKAGE_BUGREPORT='edwards@jlab.org'
 
 ac_subdirs_all="$ac_subdirs_all other_libs/intel_sse_wilson_dslash"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE RANLIB ac_ct_RANLIB QDPXX_CONFIG CXX QDPXX_CXXFLAGS QDPXX_LDFLAGS QDPXX_LIBS QDPXX_ND QDPXX_NC QDPXX_NS QDPXX_PARALLEL_ARCH QDPXX_PRECISION subdirs SSE_DSLASH_DIR BUILD_SSE_WILSON_DSLASH_TRUE BUILD_SSE_WILSON_DSLASH_FALSE BUILD_STAGGERED_LIBS_TRUE BUILD_STAGGERED_LIBS_FALSE BUILD_WILSON_LIBS_TRUE BUILD_WILSON_LIBS_FALSE CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LATEX DVIPS DVIPDF DOXYGEN LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE RANLIB ac_ct_RANLIB QDPXX_CONFIG CXX QDPXX_CXXFLAGS QDPXX_LDFLAGS QDPXX_LIBS QDPXX_ND QDPXX_NC QDPXX_NS QDPXX_PARALLEL_ARCH QDPXX_PRECISION subdirs SSE_DSLASH_DIR BUILD_SSE_WILSON_DSLASH_TRUE BUILD_SSE_WILSON_DSLASH_FALSE BUILD_PAB_WILSON_DSLASH_TRUE BUILD_PAB_WILSON_DSLASH_FALSE BUILD_STAGGERED_LIBS_TRUE BUILD_STAGGERED_LIBS_FALSE BUILD_WILSON_LIBS_TRUE BUILD_WILSON_LIBS_FALSE CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LATEX DVIPS DVIPDF DOXYGEN LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -816,6 +816,9 @@ Optional Features:
                           is wilson
   --enable-sse-wilson-dslash
                           Build and Use the SSE2 Wilson Dslash Library
+
+  --enable-pab-wilson-dslash
+                          Use PABs Wilson Dslash Library
 
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
@@ -1818,6 +1821,12 @@ if test "${enable_sse_wilson_dslash+set}" = set; then
 
 fi;
 
+# Check whether --enable-pab_wilson_dslash or --disable-pab_wilson_dslash was given.
+if test "${enable_pab_wilson_dslash+set}" = set; then
+  enableval="$enable_pab_wilson_dslash"
+
+fi;
+
 if test "X${QDPXX_HOME}X" = "XX" ; then
   # Extract the first word of "qdp++-config", so it can be a program name with args.
 set dummy qdp++-config; ac_word=$2
@@ -2028,6 +2037,43 @@ else
   BUILD_SSE_WILSON_DSLASH_TRUE='#'
   BUILD_SSE_WILSON_DSLASH_FALSE=
 fi
+
+
+case "$enable_pab_wilson_dslash" in
+  noarch)
+	ac_build_pab_wilson_dslash="yes"
+        if test "x$ac_fermion_type" != "xwilson";
+	then
+	    { { echo "$as_me:$LINENO: error:  Attempting to build Assembler Wilson Dslash with NON Wilson fermion type " >&5
+echo "$as_me: error:  Attempting to build Assembler Wilson Dslash with NON Wilson fermion type " >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+        { echo "$as_me:$LINENO: Configuring PAB Wilson Dslash  " >&5
+echo "$as_me: Configuring PAB Wilson Dslash  " >&6;}
+	cat >>confdefs.h <<\_ACEOF
+#define BUILD_PAB_WILSON_DSLASH 1
+_ACEOF
+
+	;;
+  *)
+	ac_build_pab_wilson_dslash="no"
+
+	{ echo "$as_me:$LINENO: Not building PAB Dslash  " >&5
+echo "$as_me: Not building PAB Dslash  " >&6;}
+        ;;
+esac
+
+
+
+
+if test "x${ac_build_pab_wilson_dslash}x" = "xyesx" ; then
+  BUILD_PAB_WILSON_DSLASH_TRUE=
+  BUILD_PAB_WILSON_DSLASH_FALSE='#'
+else
+  BUILD_PAB_WILSON_DSLASH_TRUE='#'
+  BUILD_PAB_WILSON_DSLASH_FALSE=
+fi
+
 
 
 
@@ -3137,6 +3183,13 @@ echo "$as_me: error: conditional \"BUILD_SSE_WILSON_DSLASH\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_PAB_WILSON_DSLASH_TRUE}" && test -z "${BUILD_PAB_WILSON_DSLASH_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_PAB_WILSON_DSLASH\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_PAB_WILSON_DSLASH\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_STAGGERED_LIBS_TRUE}" && test -z "${BUILD_STAGGERED_LIBS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_STAGGERED_LIBS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -3739,6 +3792,8 @@ s,@subdirs@,$subdirs,;t t
 s,@SSE_DSLASH_DIR@,$SSE_DSLASH_DIR,;t t
 s,@BUILD_SSE_WILSON_DSLASH_TRUE@,$BUILD_SSE_WILSON_DSLASH_TRUE,;t t
 s,@BUILD_SSE_WILSON_DSLASH_FALSE@,$BUILD_SSE_WILSON_DSLASH_FALSE,;t t
+s,@BUILD_PAB_WILSON_DSLASH_TRUE@,$BUILD_PAB_WILSON_DSLASH_TRUE,;t t
+s,@BUILD_PAB_WILSON_DSLASH_FALSE@,$BUILD_PAB_WILSON_DSLASH_FALSE,;t t
 s,@BUILD_STAGGERED_LIBS_TRUE@,$BUILD_STAGGERED_LIBS_TRUE,;t t
 s,@BUILD_STAGGERED_LIBS_FALSE@,$BUILD_STAGGERED_LIBS_FALSE,;t t
 s,@BUILD_WILSON_LIBS_TRUE@,$BUILD_WILSON_LIBS_TRUE,;t t
