Integrated AVPs double precision stuff

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -274,9 +274,10 @@ PACKAGE_STRING='chroma 3.12.0'
 PACKAGE_BUGREPORT='edwards@jlab.org'
 
 ac_subdirs_all="$ac_subdirs_all other_libs/intel_sse_wilson_dslash"
+ac_subdirs_all="$ac_subdirs_all other_libs/cg-dwf"
 ac_subdirs_all="$ac_subdirs_all other_libs/intel_sse_dwf_cg"
 ac_subdirs_all="$ac_subdirs_all other_libs/altivec_dwf_cg"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB AR ac_ct_AR QDPXX_CONFIG QDPXX_CXXFLAGS QDPXX_LDFLAGS QDPXX_LIBS QDPXX_ND QDPXX_NC QDPXX_NS QDPXX_PARALLEL_ARCH QDPXX_PRECISION subdirs SSE_DSLASH_DIR SSE_DSLASH_ENABLED BUILD_SSE_WILSON_DSLASH_TRUE BUILD_SSE_WILSON_DSLASH_FALSE SSE_DWF_CG_DIR SSE_DWF_CG_ENABLED BUILD_SSE_DWF_CG_TRUE BUILD_SSE_DWF_CG_FALSE ALTIVEC_DWF_CG_DIR ALTIVEC_DWF_CG_ENABLED BUILD_ALTIVEC_DWF_CG_TRUE BUILD_ALTIVEC_DWF_CG_FALSE BAGEL_WILSON_DSLASH_CONFIG BAGEL_WILSON_DSLASH_CXXFLAGS BAGEL_WILSON_DSLASH_LDFLAGS BAGEL_WILSON_DSLASH_LIBS BUILD_PAB_WILSON_DSLASH_TRUE BUILD_PAB_WILSON_DSLASH_FALSE BUILD_ASQTAD_CPS_INVERTER_WRAPPER_TRUE BUILD_ASQTAD_CPS_INVERTER_WRAPPER_FALSE BUILD_OPT_CFZ_LINOP_TRUE BUILD_OPT_CFZ_LINOP_FALSE GMP_CXXFLAGS GMP_LDFLAGS GMP_LIBS BUILD_GMP_REMEZ_TRUE BUILD_GMP_REMEZ_FALSE LATEX DVIPS DVIPDF DOXYGEN XMLDIFF LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB AR ac_ct_AR QDPXX_CONFIG QDPXX_CXXFLAGS QDPXX_LDFLAGS QDPXX_LIBS QDPXX_ND QDPXX_NC QDPXX_NS QDPXX_PARALLEL_ARCH QDPXX_PRECISION subdirs SSE_DSLASH_DIR SSE_DSLASH_ENABLED BUILD_SSE_WILSON_DSLASH_TRUE BUILD_SSE_WILSON_DSLASH_FALSE CG_DWF_DIR CG_DWF_ENABLED BUILD_CG_DWF_TRUE BUILD_CG_DWF_FALSE SSE_DWF_CG_DIR SSE_DWF_CG_ENABLED BUILD_SSE_DWF_CG_TRUE BUILD_SSE_DWF_CG_FALSE ALTIVEC_DWF_CG_DIR ALTIVEC_DWF_CG_ENABLED BUILD_ALTIVEC_DWF_CG_TRUE BUILD_ALTIVEC_DWF_CG_FALSE BAGEL_WILSON_DSLASH_CONFIG BAGEL_WILSON_DSLASH_CXXFLAGS BAGEL_WILSON_DSLASH_LDFLAGS BAGEL_WILSON_DSLASH_LIBS BUILD_PAB_WILSON_DSLASH_TRUE BUILD_PAB_WILSON_DSLASH_FALSE BUILD_ASQTAD_CPS_INVERTER_WRAPPER_TRUE BUILD_ASQTAD_CPS_INVERTER_WRAPPER_FALSE BUILD_OPT_CFZ_LINOP_TRUE BUILD_OPT_CFZ_LINOP_FALSE GMP_CXXFLAGS GMP_LDFLAGS GMP_LIBS BUILD_GMP_REMEZ_TRUE BUILD_GMP_REMEZ_FALSE LATEX DVIPS DVIPDF DOXYGEN XMLDIFF LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -824,6 +825,8 @@ Optional Features:
                           Build and Use the SSE2 Wilson Dslash Library
 
   --enable-sse-dwf-cg     Build and Use the SSE DWF CG Library
+
+  --enable-cg-dwf         Build and Use AVPs CG-DWF library
 
   --enable-altivec-dwf-cg Build and Use the altivec DWF CG Library
 
@@ -3289,6 +3292,12 @@ if test "${enable_sse_dwf_cg+set}" = set; then
 
 fi;
 
+# Check whether --enable-cg_dwf or --disable-cg_dwf was given.
+if test "${enable_cg_dwf+set}" = set; then
+  enableval="$enable_cg_dwf"
+
+fi;
+
 # Check whether --enable-altivec_dwf_cg or --disable-altivec_dwf_cg was given.
 if test "${enable_altivec_dwf_cg+set}" = set; then
   enableval="$enable_altivec_dwf_cg"
@@ -3629,6 +3638,44 @@ fi
 
 
 
+
+case "$enable_cg_dwf" in
+  yes)
+        { echo "$as_me:$LINENO: Configuring CG DWF" >&5
+echo "$as_me: Configuring CG DWF" >&6;}
+
+
+subdirs="$subdirs other_libs/cg-dwf"
+
+	CG_DWF_DIR=cg-dwf
+
+
+cat >>confdefs.h <<\_ACEOF
+#define BUILD_CG_DWF 1
+_ACEOF
+
+	;;
+  *)
+
+	{ echo "$as_me:$LINENO: Not building CG DWF" >&5
+echo "$as_me: Not building CG DWF" >&6;}
+        ;;
+esac
+CG_DWF_ENABLED=$enable_cg_dwf
+
+
+
+
+if test "x${enable_cg_dwf}x" = "xyesx" ; then
+  BUILD_CG_DWF_TRUE=
+  BUILD_CG_DWF_FALSE='#'
+else
+  BUILD_CG_DWF_TRUE='#'
+  BUILD_CG_DWF_FALSE=
+fi
+
+
+
 case "$enable_sse_dwf_cg" in
   yes)
         { echo "$as_me:$LINENO: Configuring SSE DWF CG" >&5
@@ -3663,6 +3710,7 @@ else
   BUILD_SSE_DWF_CG_TRUE='#'
   BUILD_SSE_DWF_CG_FALSE=
 fi
+
 
 
 
@@ -4544,6 +4592,13 @@ echo "$as_me: error: conditional \"BUILD_SSE_WILSON_DSLASH\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_CG_DWF_TRUE}" && test -z "${BUILD_CG_DWF_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_CG_DWF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_CG_DWF\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_SSE_DWF_CG_TRUE}" && test -z "${BUILD_SSE_DWF_CG_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_SSE_DWF_CG\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -5191,6 +5246,10 @@ s,@SSE_DSLASH_DIR@,$SSE_DSLASH_DIR,;t t
 s,@SSE_DSLASH_ENABLED@,$SSE_DSLASH_ENABLED,;t t
 s,@BUILD_SSE_WILSON_DSLASH_TRUE@,$BUILD_SSE_WILSON_DSLASH_TRUE,;t t
 s,@BUILD_SSE_WILSON_DSLASH_FALSE@,$BUILD_SSE_WILSON_DSLASH_FALSE,;t t
+s,@CG_DWF_DIR@,$CG_DWF_DIR,;t t
+s,@CG_DWF_ENABLED@,$CG_DWF_ENABLED,;t t
+s,@BUILD_CG_DWF_TRUE@,$BUILD_CG_DWF_TRUE,;t t
+s,@BUILD_CG_DWF_FALSE@,$BUILD_CG_DWF_FALSE,;t t
 s,@SSE_DWF_CG_DIR@,$SSE_DWF_CG_DIR,;t t
 s,@SSE_DWF_CG_ENABLED@,$SSE_DWF_CG_ENABLED,;t t
 s,@BUILD_SSE_DWF_CG_TRUE@,$BUILD_SSE_DWF_CG_TRUE,;t t
