added altivec dwf cg inverter. This is a modification of A. Pochinsky's SSE DWF CG

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -275,7 +275,8 @@ PACKAGE_BUGREPORT='edwards@jlab.org'
 
 ac_subdirs_all="$ac_subdirs_all other_libs/intel_sse_wilson_dslash"
 ac_subdirs_all="$ac_subdirs_all other_libs/intel_sse_dwf_cg"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB AR ac_ct_AR QDPXX_CONFIG QDPXX_CXXFLAGS QDPXX_LDFLAGS QDPXX_LIBS QDPXX_ND QDPXX_NC QDPXX_NS QDPXX_PARALLEL_ARCH QDPXX_PRECISION subdirs SSE_DSLASH_DIR SSE_DSLASH_ENABLED BUILD_SSE_WILSON_DSLASH_TRUE BUILD_SSE_WILSON_DSLASH_FALSE SSE_DWF_CG_DIR SSE_DWF_CG_ENABLED BUILD_SSE_DWF_CG_TRUE BUILD_SSE_DWF_CG_FALSE BAGEL_WILSON_DSLASH_CONFIG BAGEL_WILSON_DSLASH_CXXFLAGS BAGEL_WILSON_DSLASH_LDFLAGS BAGEL_WILSON_DSLASH_LIBS BUILD_PAB_WILSON_DSLASH_TRUE BUILD_PAB_WILSON_DSLASH_FALSE BUILD_ASQTAD_CPS_INVERTER_WRAPPER_TRUE BUILD_ASQTAD_CPS_INVERTER_WRAPPER_FALSE BUILD_OPT_CFZ_LINOP_TRUE BUILD_OPT_CFZ_LINOP_FALSE GMP_CXXFLAGS GMP_LDFLAGS GMP_LIBS BUILD_GMP_REMEZ_TRUE BUILD_GMP_REMEZ_FALSE LATEX DVIPS DVIPDF DOXYGEN LIBOBJS LTLIBOBJS'
+ac_subdirs_all="$ac_subdirs_all other_libs/altivec_dwf_cg"
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB AR ac_ct_AR QDPXX_CONFIG QDPXX_CXXFLAGS QDPXX_LDFLAGS QDPXX_LIBS QDPXX_ND QDPXX_NC QDPXX_NS QDPXX_PARALLEL_ARCH QDPXX_PRECISION subdirs SSE_DSLASH_DIR SSE_DSLASH_ENABLED BUILD_SSE_WILSON_DSLASH_TRUE BUILD_SSE_WILSON_DSLASH_FALSE SSE_DWF_CG_DIR SSE_DWF_CG_ENABLED BUILD_SSE_DWF_CG_TRUE BUILD_SSE_DWF_CG_FALSE ALTIVEC_DWF_CG_DIR ALTIVEC_DWF_CG_ENABLED BUILD_ALTIVEC_DWF_CG_TRUE BUILD_ALTIVEC_DWF_CG_FALSE BAGEL_WILSON_DSLASH_CONFIG BAGEL_WILSON_DSLASH_CXXFLAGS BAGEL_WILSON_DSLASH_LDFLAGS BAGEL_WILSON_DSLASH_LIBS BUILD_PAB_WILSON_DSLASH_TRUE BUILD_PAB_WILSON_DSLASH_FALSE BUILD_ASQTAD_CPS_INVERTER_WRAPPER_TRUE BUILD_ASQTAD_CPS_INVERTER_WRAPPER_FALSE BUILD_OPT_CFZ_LINOP_TRUE BUILD_OPT_CFZ_LINOP_FALSE GMP_CXXFLAGS GMP_LDFLAGS GMP_LIBS BUILD_GMP_REMEZ_TRUE BUILD_GMP_REMEZ_FALSE LATEX DVIPS DVIPDF DOXYGEN LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -823,6 +824,8 @@ Optional Features:
                           Build and Use the SSE2 Wilson Dslash Library
 
   --enable-sse-dwf-cg     Build and Use the SSE DWF CG Library
+
+  --enable-altivec-dwf-cg Build and Use the altivec DWF CG Library
 
   --enable-asqtad-cps-inverter
                           Wrap the CPS asqtad inverter
@@ -3283,6 +3286,12 @@ if test "${enable_sse_dwf_cg+set}" = set; then
 
 fi;
 
+# Check whether --enable-altivec_dwf_cg or --disable-altivec_dwf_cg was given.
+if test "${enable_altivec_dwf_cg+set}" = set; then
+  enableval="$enable_altivec_dwf_cg"
+
+fi;
+
 
 # Check whether --with-bagel_wilson_dslash or --without-bagel_wilson_dslash was given.
 if test "${with_bagel_wilson_dslash+set}" = set; then
@@ -3642,6 +3651,44 @@ else
   BUILD_SSE_DWF_CG_TRUE='#'
   BUILD_SSE_DWF_CG_FALSE=
 fi
+
+
+
+case "$enable_altivec_dwf_cg" in
+  yes)
+        { echo "$as_me:$LINENO: Configuring ALTIVEC DWF CG" >&5
+echo "$as_me: Configuring ALTIVEC DWF CG" >&6;}
+
+
+subdirs="$subdirs other_libs/altivec_dwf_cg"
+
+	ALTIVEC_DWF_CG_DIR=altivec_dwf_cg
+
+
+cat >>confdefs.h <<\_ACEOF
+#define BUILD_ALTIVEC_DWF_CG 1
+_ACEOF
+
+	;;
+  *)
+
+	{ echo "$as_me:$LINENO: Not building ALTIVEC DWF CG" >&5
+echo "$as_me: Not building ALTIVEC DWF CG" >&6;}
+        ;;
+esac
+ALTIVEC_DWF_CG_ENABLED=$enable_altivec_dwf_cg
+
+
+
+
+if test "x${enable_altivec_dwf_cg}x" = "xyesx" ; then
+  BUILD_ALTIVEC_DWF_CG_TRUE=
+  BUILD_ALTIVEC_DWF_CG_FALSE='#'
+else
+  BUILD_ALTIVEC_DWF_CG_TRUE='#'
+  BUILD_ALTIVEC_DWF_CG_FALSE=
+fi
+
 
 
 
@@ -4421,6 +4468,13 @@ echo "$as_me: error: conditional \"BUILD_SSE_DWF_CG\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${BUILD_ALTIVEC_DWF_CG_TRUE}" && test -z "${BUILD_ALTIVEC_DWF_CG_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_ALTIVEC_DWF_CG\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_ALTIVEC_DWF_CG\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_PAB_WILSON_DSLASH_TRUE}" && test -z "${BUILD_PAB_WILSON_DSLASH_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_PAB_WILSON_DSLASH\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -5054,6 +5108,10 @@ s,@SSE_DWF_CG_DIR@,$SSE_DWF_CG_DIR,;t t
 s,@SSE_DWF_CG_ENABLED@,$SSE_DWF_CG_ENABLED,;t t
 s,@BUILD_SSE_DWF_CG_TRUE@,$BUILD_SSE_DWF_CG_TRUE,;t t
 s,@BUILD_SSE_DWF_CG_FALSE@,$BUILD_SSE_DWF_CG_FALSE,;t t
+s,@ALTIVEC_DWF_CG_DIR@,$ALTIVEC_DWF_CG_DIR,;t t
+s,@ALTIVEC_DWF_CG_ENABLED@,$ALTIVEC_DWF_CG_ENABLED,;t t
+s,@BUILD_ALTIVEC_DWF_CG_TRUE@,$BUILD_ALTIVEC_DWF_CG_TRUE,;t t
+s,@BUILD_ALTIVEC_DWF_CG_FALSE@,$BUILD_ALTIVEC_DWF_CG_FALSE,;t t
 s,@BAGEL_WILSON_DSLASH_CONFIG@,$BAGEL_WILSON_DSLASH_CONFIG,;t t
 s,@BAGEL_WILSON_DSLASH_CXXFLAGS@,$BAGEL_WILSON_DSLASH_CXXFLAGS,;t t
 s,@BAGEL_WILSON_DSLASH_LDFLAGS@,$BAGEL_WILSON_DSLASH_LDFLAGS,;t t
