Induced changes.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -701,6 +701,9 @@ BAGEL_CLOVER_LDFLAGS
 BAGEL_CLOVER_LIBS
 BUILD_BAGEL_CLOVER_APPLY_TRUE
 BUILD_BAGEL_CLOVER_APPLY_FALSE
+LAPACK_ENABLED
+BUILD_LAPACK_TRUE
+BUILD_LAPACK_FALSE
 BUILD_ASQTAD_LEVEL3_INVERTER_WRAPPER_TRUE
 BUILD_ASQTAD_LEVEL3_INVERTER_WRAPPER_FALSE
 BUILD_OPT_CFZ_LINOP_TRUE
@@ -1329,6 +1332,8 @@ Optional Features:
   --enable-bagel-wilson-dslash-sloppy
                           Enable Sloppy Precision in BAGEL Dslash -- different
                           internal and external precisions
+  --enable-lapack=<type>  Use the type of lapack bindings specified by <type>.
+                          Currently, this can be lapack
   --enable-opt-cfz-linop  Build and use the generic optimized Continued Frac.
                           Zolo. (CFZ) Linear Oper.
 
@@ -3924,6 +3929,12 @@ if test "${with_bagel_clover+set}" = set; then
 fi
 
 
+# Check whether --enable-lapack was given.
+if test "${enable_lapack+set}" = set; then
+  enableval=$enable_lapack; LAPACK_BINDING="${enableval}"
+
+fi
+
 
 # Check whether --enable-opt_cfz_linop was given.
 if test "${enable_opt_cfz_linop+set}" = set; then
@@ -4267,6 +4278,7 @@ else
   BUILD_SSE_WILSON_DSLASH_TRUE='#'
   BUILD_SSE_WILSON_DSLASH_FALSE=
 fi
+
 
 
 if  test "x${build_cg_dwf}x" = "xyesx" ;
@@ -4636,6 +4648,7 @@ else
 fi
 
 
+
 if test "X${bagel_clover_enabled}X" = "XyesX";
 then
    { echo "$as_me:$LINENO: Configuring with BAGEL Clover Apply " >&5
@@ -4878,6 +4891,35 @@ else
   BUILD_BAGEL_CLOVER_APPLY_FALSE=
 fi
 
+
+
+case "${LAPACK_BINDING}" in
+lapack)
+	{ echo "$as_me:$LINENO: Configuring to use Lapack. This will turn on some additional system solvers." >&5
+echo "$as_me: Configuring to use Lapack. This will turn on some additional system solvers." >&6;}
+
+cat >>confdefs.h <<\_ACEOF
+#define BUILD_LAPACK
+_ACEOF
+
+        LAPACK_ENABLED=yes
+
+	;;
+*)
+	{ echo "$as_me:$LINENO: Will not use Lapack." >&5
+echo "$as_me: Will not use Lapack." >&6;}
+        LAPACK_ENABLED=no
+
+	;;
+esac
+
+ if  test "X${LAPACK_ENABLED}X" = "XyesX" ; then
+  BUILD_LAPACK_TRUE=
+  BUILD_LAPACK_FALSE='#'
+else
+  BUILD_LAPACK_TRUE='#'
+  BUILD_LAPACK_FALSE=
+fi
 
 
 
@@ -5568,6 +5610,13 @@ if test -z "${BUILD_BAGEL_CLOVER_APPLY_TRUE}" && test -z "${BUILD_BAGEL_CLOVER_A
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_BAGEL_CLOVER_APPLY\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_BAGEL_CLOVER_APPLY\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_LAPACK_TRUE}" && test -z "${BUILD_LAPACK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_LAPACK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_LAPACK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -6308,6 +6357,9 @@ BAGEL_CLOVER_LDFLAGS!$BAGEL_CLOVER_LDFLAGS$ac_delim
 BAGEL_CLOVER_LIBS!$BAGEL_CLOVER_LIBS$ac_delim
 BUILD_BAGEL_CLOVER_APPLY_TRUE!$BUILD_BAGEL_CLOVER_APPLY_TRUE$ac_delim
 BUILD_BAGEL_CLOVER_APPLY_FALSE!$BUILD_BAGEL_CLOVER_APPLY_FALSE$ac_delim
+LAPACK_ENABLED!$LAPACK_ENABLED$ac_delim
+BUILD_LAPACK_TRUE!$BUILD_LAPACK_TRUE$ac_delim
+BUILD_LAPACK_FALSE!$BUILD_LAPACK_FALSE$ac_delim
 BUILD_ASQTAD_LEVEL3_INVERTER_WRAPPER_TRUE!$BUILD_ASQTAD_LEVEL3_INVERTER_WRAPPER_TRUE$ac_delim
 BUILD_ASQTAD_LEVEL3_INVERTER_WRAPPER_FALSE!$BUILD_ASQTAD_LEVEL3_INVERTER_WRAPPER_FALSE$ac_delim
 BUILD_OPT_CFZ_LINOP_TRUE!$BUILD_OPT_CFZ_LINOP_TRUE$ac_delim
@@ -6332,7 +6384,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 48; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 51; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
